Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /summit HTTP/1.1" 301 0
Internal Server Error: /summit/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_response(request, response)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
AttributeError: 'SummitData' object has no attribute 'get'
"GET /summit/ HTTP/1.1" 500 145
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 179
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /summit/ HTTP/1.1" 200 3327
"POST /summit/ HTTP/1.1" 302 0
Internal Server Error: /summit/list
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
"GET /summit/list HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/models.py changed, reloading.
Watching for file changes with StatReloader
"GET /summit/ HTTP/1.1" 200 3327
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /summit/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/summit/views.py", line 31, in summit_form
    return render(request, 'summit/form.html', context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /summit/ HTTP/1.1" 500 145
"GET /summit/ HTTP/1.1" 200 3355
"POST /summit/ HTTP/1.1" 302 0
Internal Server Error: /summit/list
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
"GET /summit/list HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /summit/list
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
"GET /summit/list HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /summit/list HTTP/1.1" 301 0
Internal Server Error: /summit/list/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
"GET /summit/list/ HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /summit/list/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /summit/list/ HTTP/1.1" 500 145
Internal Server Error: /summit/list/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'task-update' not found. 'task-update' is not a valid view function or pattern name.
"GET /summit/list/ HTTP/1.1" 500 145
"GET /summit/list/ HTTP/1.1" 200 3316
"GET /logout HTTP/1.1" 301 0
"GET /logout/ HTTP/1.1" 302 0
"GET /login HTTP/1.1" 301 0
"GET /login/ HTTP/1.1" 200 2845
"POST /login/ HTTP/1.1" 200 3033
"POST /login/ HTTP/1.1" 200 3033
"GET /sign-up HTTP/1.1" 200 3907
"POST /sign-up HTTP/1.1" 200 4196
"POST /sign-up HTTP/1.1" 200 4070
"POST /sign-up HTTP/1.1" 200 4080
"POST /sign-up HTTP/1.1" 302 0
"GET /home HTTP/1.1" 200 2000
"GET /summit/list/ HTTP/1.1" 200 3316
"POST /summit/1/delete/ HTTP/1.1" 302 0
"GET /summit/list/ HTTP/1.1" 200 2762
"GET /summit/2/update/ HTTP/1.1" 200 3537
"GET / HTTP/1.1" 302 0
"GET /login?next=/ HTTP/1.1" 301 0
"GET /login/?next=/ HTTP/1.1" 200 2845
Not Found: /.git/config
"GET /.git/config HTTP/1.1" 404 179
Not Found: /demo/.git/config
"GET /demo/.git/config HTTP/1.1" 404 179
Not Found: /dev/.git/config
"GET /dev/.git/config HTTP/1.1" 404 179
Not Found: /web/.git/config
"GET /web/.git/config HTTP/1.1" 404 179
Not Found: /api/.git/config
"GET /api/.git/config HTTP/1.1" 404 179
"GET /admin/.git/config HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/.git/config HTTP/1.1" 200 2240
Not Found: /app/.git/config
"GET /app/.git/config HTTP/1.1" 404 179
code 400, message Bad request version ("ð\x95vÀ\x17\x1bÂêû\x91\x05\x18${\x1aa\x00V\x13\x02\x13\x03\x13\x01À,À0À+À/Ì©Ì¨\x00\x9f\x00\x9eÌªÀ¯À\xadÀ®À¬À$À(À#À'À")
You're accessing the development server over HTTPS, but it only supports HTTP.
"GET / HTTP/1.1" 302 0
"GET /login?next=/ HTTP/1.1" 301 0
"GET /login/?next=/ HTTP/1.1" 200 2845
code 400, message Bad request syntax ('MGLNDD_54.250.195.214_8000')
"MGLNDD_54.250.195.214_8000" 400 -
"GET /upload HTTP/1.1" 302 0
"GET /login?next=/upload HTTP/1.1" 301 0
"GET /login/?next=/upload HTTP/1.1" 200 2845
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 179
"POST /login/?next=/upload HTTP/1.1" 302 0
"POST /login/?next=/upload HTTP/1.1" 302 0
"GET /upload HTTP/1.1" 200 2787
"GET /summit/ HTTP/1.1" 200 3355
"POST /summit/ HTTP/1.1" 302 0
"GET /summit/list/ HTTP/1.1" 200 3291
"POST /summit/2/delete/ HTTP/1.1" 302 0
"GET /summit/list/ HTTP/1.1" 200 2744
"GET /upload HTTP/1.1" 200 2787
code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00u\x01\x00\x00q\x03\x03Ò.@C9ó\x15×\x01\x06\x13\x8aÂû\x02mñø¯¬Ú_f\x08ù.K»¹Ú¿-\x00\x00\x1aÀ/À+À\x11À\x07À\x13À')
You're accessing the development server over HTTPS, but it only supports HTTP.
"GET / HTTP/1.1" 302 0
"GET /login?next=/ HTTP/1.1" 301 0
"GET /login/?next=/ HTTP/1.1" 200 2845
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 179
"GET /summit/list/ HTTP/1.1" 200 2744
"GET /summit/list/ HTTP/1.1" 200 2900
"GET /summit/list/ HTTP/1.1" 200 2886
"GET /summit/list/ HTTP/1.1" 200 2886
"GET /logout/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 2987
"POST /login/ HTTP/1.1" 302 0
"GET /home HTTP/1.1" 200 2142
"GET /summit/list/ HTTP/1.1" 200 2885
"GET /summit/3/update/ HTTP/1.1" 200 3661
"GET /summit/list/ HTTP/1.1" 200 2885
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 200 4481
"GET /static/admin/css/base.css HTTP/1.1" 200 20344
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 796
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2619
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18854
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3763
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /admin/auth/group/ HTTP/1.1" 200 6350
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6395
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/core.js HTTP/1.1" 200 5698
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8985
"GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 200 89501
"GET /static/admin/js/actions.js HTTP/1.1" 200 7872
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/filters.js HTTP/1.1" 200 966
"GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 200 125266
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/auth/group/add/ HTTP/1.1" 200 9411
"GET /static/admin/css/forms.css HTTP/1.1" 200 8944
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 11317
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11297
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 6754
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /admin/auth/user/ HTTP/1.1" 200 10060
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 17711
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19379
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 10253
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/user/1/change/ HTTP/1.1" 200 17366
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"POST /admin/auth/user/1/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 10252
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/user/4/change/ HTTP/1.1" 200 17363
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"POST /admin/logout/ HTTP/1.1" 302 0
"GET /login HTTP/1.1" 301 0
"GET /login/ HTTP/1.1" 200 2987
"POST /login/ HTTP/1.1" 200 3175
"POST /login/ HTTP/1.1" 200 3175
"POST /login/ HTTP/1.1" 200 3175
"POST /login/ HTTP/1.1" 302 0
"GET /home HTTP/1.1" 200 2142
"GET /admin/ HTTP/1.1" 200 5323
"GET /admin/auth/user/ HTTP/1.1" 200 10060
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/user/2/change/ HTTP/1.1" 200 17792
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/group/ HTTP/1.1" 200 6557
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/user/ HTTP/1.1" 200 10060
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/user/1/change/ HTTP/1.1" 200 17375
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Internal Server Error: /admin/auth/user/1/delete/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'TextLists.projects' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2110, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2138, in _delete_view
    ) = self.get_deleted_objects([obj], request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2105, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 120, in get_deleted_objects
    collector.collect(objs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 186, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/deletion.py", line 343, in collect
    if sub_objs:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 408, in __bool__
    self._fetch_all()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'TextLists.projects' doesn't exist")
"GET /admin/auth/user/1/delete/ HTTP/1.1" 500 145
Internal Server Error: /admin/auth/user/1/delete/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'TextLists.projects' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2110, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2138, in _delete_view
    ) = self.get_deleted_objects([obj], request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2105, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 120, in get_deleted_objects
    collector.collect(objs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 186, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/deletion.py", line 343, in collect
    if sub_objs:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 408, in __bool__
    self._fetch_all()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'TextLists.projects' doesn't exist")
"GET /admin/auth/user/1/delete/ HTTP/1.1" 500 145
"GET /admin/auth/user/1/change/ HTTP/1.1" 200 17375
"GET /admin/auth/user/ HTTP/1.1" 200 10060
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/user/1/change/ HTTP/1.1" 200 17375
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Internal Server Error: /admin/auth/user/1/delete/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'TextLists.projects' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2110, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2138, in _delete_view
    ) = self.get_deleted_objects([obj], request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/options.py", line 2105, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 120, in get_deleted_objects
    collector.collect(objs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 186, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/deletion.py", line 343, in collect
    if sub_objs:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 408, in __bool__
    self._fetch_all()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'TextLists.projects' doesn't exist")
"GET /admin/auth/user/1/delete/ HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: "user.groups.filter(name='timesheet').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 36, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 952, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 885, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 888, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='timesheet').exists' from 'user.groups.filter(name='timesheet').exists'
"GET / HTTP/1.1" 500 145
"GET /admin/ HTTP/1.1" 200 5323
"GET /admin/auth/group/ HTTP/1.1" 200 6557
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
/home/ubuntu/OneForAll/website/main/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/admin.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: "user.groups.filter(name='timesheet').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/admin.py", line 8, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 952, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 885, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 888, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='timesheet').exists' from 'user.groups.filter(name='timesheet').exists'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: "request.user.groups.filter(name='timesheet').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/admin.py", line 8, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 952, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 885, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 888, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='timesheet').exists' from 'request.user.groups.filter(name='timesheet').exists'
"GET / HTTP/1.1" 500 145
"GET /admin/auth/group/ HTTP/1.1" 200 6557
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: "request.user.groups.filter(name='timesheet').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/admin.py", line 8, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 952, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 885, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 888, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='timesheet').exists' from 'request.user.groups.filter(name='timesheet').exists'
"GET / HTTP/1.1" 500 145
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: 'request.user|is_timesheet_user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/admin.py", line 8, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 952, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 885, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 888, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'is_timesheet_user'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'auth_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/admin.py", line 8, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'auth_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'auth_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/admin.py", line 8, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'auth_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'auth_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/admin.py", line 8, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'auth_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'auth_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/admin.py", line 8, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'auth_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
"GET / HTTP/1.1" 500 145
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2205
"GET / HTTP/1.1" 200 2188
"GET /logout/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 2873
"POST /login/ HTTP/1.1" 302 0
Forbidden: /home
"GET /home HTTP/1.1" 403 46
"GET /admin/auth/user/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/auth/user/ HTTP/1.1" 200 2390
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"POST /admin/login/?next=/admin/auth/user/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 10060
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/user/4/change/ HTTP/1.1" 200 17363
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 10253
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /home HTTP/1.1" 200 2188
"GET /logout/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 2873
"GET /login/ HTTP/1.1" 200 2873
"POST /login/ HTTP/1.1" 200 3062
"POST /login/ HTTP/1.1" 302 0
Forbidden: /home
"GET /home HTTP/1.1" 403 46
"GET /upload HTTP/1.1" 302 0
"GET /login?next=/upload HTTP/1.1" 301 0
"GET /login/?next=/upload HTTP/1.1" 200 2873
"POST /login/?next=/upload HTTP/1.1" 302 0
"GET /upload HTTP/1.1" 200 2975
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 200 5603
"GET /static/admin/css/base.css HTTP/1.1" 200 20344
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 796
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2619
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18854
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3763
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /admin/auth/group/ HTTP/1.1" 200 6557
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6395
"GET /static/admin/js/core.js HTTP/1.1" 200 5698
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8985
"GET /static/admin/js/actions.js HTTP/1.1" 200 7872
"GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 200 89501
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
"GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 200 125266
"GET /static/admin/js/filters.js HTTP/1.1" 200 966
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/auth/user/ HTTP/1.1" 200 10060
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /admin/auth/user/4/change/ HTTP/1.1" 200 17372
"GET /static/admin/css/forms.css HTTP/1.1" 200 8944
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19379
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 11317
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11297
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
Forbidden: /home
"GET /home HTTP/1.1" 403 46
"POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 10253
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/user/4/change/ HTTP/1.1" 200 17381
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /home HTTP/1.1" 200 2188
Internal Server Error: /home
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 179, in translate_token
    op = OPERATORS[token]
KeyError: "user.groups.filter(name='timesheet').exists"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/admin.py", line 8, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 952, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 885, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/smartif.py", line 181, in translate_token
    return self.create_var(token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 888, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='timesheet').exists' from 'user.groups.filter(name='timesheet').exists'
"GET /home HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/main/templatetags/auth_tags.py changed, reloading.
Watching for file changes with StatReloader
"GET /home HTTP/1.1" 200 2198
"POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 10253
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Forbidden: /home
"GET /home HTTP/1.1" 403 46
Forbidden: /home
"GET /home HTTP/1.1" 403 46
Forbidden: /home
"GET /home HTTP/1.1" 403 46
Forbidden: /home
"GET /home HTTP/1.1" 403 46
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 200 6163
"POST /admin/logout/ HTTP/1.1" 302 0
"GET /login HTTP/1.1" 301 0
Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 14: 'static'. Did you forget to register or load this tag?
"GET /login/ HTTP/1.1" 500 145
"GET /login/ HTTP/1.1" 200 3106
Not Found: /login/static/js/myscript.js
"GET /login/static/js/myscript.js HTTP/1.1" 404 179
"GET /static/js/myscript.js HTTP/1.1" 200 0
"GET /summit/list/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/list/ HTTP/1.1" 404 179
"GET /login/ HTTP/1.1" 200 3106
"POST /login/ HTTP/1.1" 302 0
"GET /home HTTP/1.1" 200 2261
"GET /logout HTTP/1.1" 301 0
"GET /logout/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 3106
Not Found: /login/static/js/myscript.js
"GET /login/static/js/myscript.js HTTP/1.1" 404 179
"POST /login/ HTTP/1.1" 302 0
Forbidden: /home
"GET /home HTTP/1.1" 403 46
Forbidden: /home
"GET /home HTTP/1.1" 403 46
Forbidden: /home
"GET /home HTTP/1.1" 403 46
/home/ubuntu/OneForAll/website/main/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /home HTTP/1.1" 200 2207
"GET /summit/list/ HTTP/1.1" 200 2950
Watching for file changes with StatReloader
"GET /admin/auth/user/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/auth/user/ HTTP/1.1" 200 2390
"GET /summit/list/ HTTP/1.1" 200 2950
"GET /static/js/myscript.js HTTP/1.1" 200 250
Watching for file changes with StatReloader
"GET /admin/auth/user/4/change/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/auth/user/4/change/ HTTP/1.1" 200 2408
"GET / HTTP/1.1" 200 2729
"GET /static/js/myscript.js HTTP/1.1" 200 250
"GET / HTTP/1.1" 200 2674
"GET / HTTP/1.1" 200 2674
"GET / HTTP/1.1" 200 2728
"GET / HTTP/1.1" 200 2696
"GET / HTTP/1.1" 200 2823
"GET / HTTP/1.1" 200 2853
"GET / HTTP/1.1" 200 2854
"GET / HTTP/1.1" 200 2846
"GET /admin/auth/user/4/change/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/auth/user/4/change/ HTTP/1.1" 200 2408
"GET /static/admin/css/base.css HTTP/1.1" 200 20344
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 796
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2619
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3763
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18854
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"POST /admin/login/?next=/admin/auth/user/4/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/4/change/ HTTP/1.1" 200 17372
"GET /static/admin/css/forms.css HTTP/1.1" 200 8944
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19379
"GET /static/admin/js/core.js HTTP/1.1" 200 5698
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11297
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8985
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
"GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 200 89501
"GET /static/admin/js/actions.js HTTP/1.1" 200 7872
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 11317
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 200 125266
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /admin/auth/group/add/ HTTP/1.1" 200 9411
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 6954
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6395
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/filters.js HTTP/1.1" 200 966
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /admin/auth/user/ HTTP/1.1" 200 10123
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /admin/auth/user/4/change/ HTTP/1.1" 200 17409
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"POST /admin/auth/user/4/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 10316
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET / HTTP/1.1" 200 2863
"GET / HTTP/1.1" 200 2859
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 673, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: user.groups.all.values_list|('name', flat=True)||safe
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('name', flat=True)' from 'user.groups.all.values_list('name', flat=True)'
"GET / HTTP/1.1" 500 145
"GET / HTTP/1.1" 200 2859
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 673, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: user.groups.all.values_list|('name', flat=True)||json
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 698, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'json'
"GET / HTTP/1.1" 500 145
"GET / HTTP/1.1" 200 2721
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 484, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 673, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: user.groups.all.values_list|('name', flat=True)| | list
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1482, in do_with
    extra_context = token_kwargs(remaining_bits, parser, support_legacy=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1116, in token_kwargs
    kwargs[key] = parser.compile_filter(value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('name',' from 'user.groups.all.values_list('name','
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1482, in do_with
    extra_context = token_kwargs(remaining_bits, parser, support_legacy=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1116, in token_kwargs
    kwargs[key] = parser.compile_filter(value)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('name',' from 'user.groups.all.values_list('name','
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'user_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'user_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'user_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/main/views.py", line 37, in home
    return render(request, 'main/home.html', {'posts': posts})
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'user_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
i18n
l10n
log
static
tz
"GET / HTTP/1.1" 500 145
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2095
"GET /summit/list/ HTTP/1.1" 200 2775
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /summit/list/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/list/ HTTP/1.1" 404 179
"GET /summit/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/ HTTP/1.1" 404 179
"GET /summit/ HTTP/1.1" 200 3573
"GET /summit/list/ HTTP/1.1" 200 2961
/home/ubuntu/OneForAll/website/summit/admin.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/main/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /summit/list/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/home/ubuntu/OneForAll/website/summit/views.py", line 42, in get_queryset
    return SummitData.objects.filter(user=self.request.user)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1407, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1217, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1709, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'user' into field. Choices are: city, id, medium, project_code, summit_password, summit_username, task_name, task_notes
"GET /summit/list/ HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/models.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /summit/list/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'summit_summitdata.user_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 194, in render
    len_values = len(values)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'summit_summitdata.user_id' in 'field list'")
"GET /summit/list/ HTTP/1.1" 500 145
Internal Server Error: /summit/list/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'summit_summitdata.user_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 194, in render
    len_values = len(values)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'summit_summitdata.user_id' in 'field list'")
"GET /summit/list/ HTTP/1.1" 500 145
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /summit/entry
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/OneForAll/website/summit/views.py", line 61, in entry
    dataDict = model_to_dict(myData)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/forms/models.py", line 105, in model_to_dict
    opts = instance._meta
AttributeError: 'QuerySet' object has no attribute '_meta'
"GET /summit/entry HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /summit HTTP/1.1" 301 0
"GET /summit/ HTTP/1.1" 200 3573
Internal Server Error: /summit/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'user_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/summit/views.py", line 28, in summit_form
    summit_data.save()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'user_id' in 'field list'")
"POST /summit/ HTTP/1.1" 500 145
"POST /summit/ HTTP/1.1" 302 0
"GET /summit/list/ HTTP/1.1" 200 2432
Internal Server Error: /summit/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'user_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/summit/views.py", line 28, in summit_form
    summit_data.save()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'user_id' in 'field list'")
"POST /summit/ HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /summit/ HTTP/1.1" 200 3911
Internal Server Error: /summit/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'user_id' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/summit/views.py", line 28, in summit_form
    summit_data.save()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'user_id' in 'field list'")
"POST /summit/ HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/forms.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /summit/ HTTP/1.1" 200 3573
Internal Server Error: /summit/list/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'TextLists.summit_summitdata' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 194, in render
    len_values = len(values)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'TextLists.summit_summitdata' doesn't exist")
"GET /summit/list/ HTTP/1.1" 500 145
Watching for file changes with StatReloader
"GET /summit/list/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/list/ HTTP/1.1" 404 179
"GET / HTTP/1.1" 302 0
"GET /login?next=/ HTTP/1.1" 301 0
"GET /login/?next=/ HTTP/1.1" 200 2877
"POST /login/?next=/ HTTP/1.1" 200 3066
"GET /sign-up HTTP/1.1" 200 3939
Watching for file changes with StatReloader
"GET /upload HTTP/1.1" 302 0
"GET /login?next=/upload HTTP/1.1" 301 0
"GET /login/?next=/upload HTTP/1.1" 200 2877
"POST /login/?next=/upload HTTP/1.1" 200 3066
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 2379
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 3580
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET / HTTP/1.1" 200 2032
"GET /summit/list/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/list/ HTTP/1.1" 404 179
"GET /admin/ HTTP/1.1" 200 3580
"GET /admin/auth/group/ HTTP/1.1" 200 5208
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/group/add/ HTTP/1.1" 200 9411
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 6545
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/group/add/ HTTP/1.1" 200 9411
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 6754
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/group/add/ HTTP/1.1" 200 9411
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"POST /admin/auth/group/add/ HTTP/1.1" 302 0
"GET /admin/auth/group/ HTTP/1.1" 200 6952
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET / HTTP/1.1" 200 2032
"GET /summit/list/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/list/ HTTP/1.1" 404 179
"GET /admin/auth/user/ HTTP/1.1" 200 8882
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/user/1/change/ HTTP/1.1" 200 17414
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"POST /admin/auth/user/1/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 9075
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/list/ HTTP/1.1" 404 179
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/list/ HTTP/1.1" 404 179
"GET / HTTP/1.1" 200 2218
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET /login?next=/ HTTP/1.1" 301 0
Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Bad Request: /http:/api.ipify.org/
"GET http://api.ipify.org/?format=json HTTP/1.1" 400 143
Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Bad Request: /www.shadowserver.org:443
"CONNECT www.shadowserver.org:443 HTTP/1.1" 400 143
"GET /upload HTTP/1.1" 302 0
"GET /login?next=/upload HTTP/1.1" 301 0
"GET /login/?next=/upload HTTP/1.1" 200 2877
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 179
"POST /login/?next=/upload HTTP/1.1" 200 3066
"POST /login/?next=/upload HTTP/1.1" 302 0
"GET /upload HTTP/1.1" 200 3005
"GET /admin/ HTTP/1.1" 200 4736
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/fonts.css HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
"GET /admin/auth/group/ HTTP/1.1" 200 6759
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /admin/auth/user/ HTTP/1.1" 200 9319
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /summit/ HTTP/1.1" 200 3573
"GET /summit/list/ HTTP/1.1" 200 2432
"GET /summit/list/ HTTP/1.1" 200 2432
"GET /summit/list/ HTTP/1.1" 200 2467
"GET /summit/ HTTP/1.1" 200 3573
Internal Server Error: /summit/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'user_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/OneForAll/website/summit/views.py", line 28, in summit_form
    summit_data.save()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
"POST /summit/ HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /summit/ HTTP/1.1" 302 0
"GET /summit/list/ HTTP/1.1" 200 3030
"GET /logout/ HTTP/1.1" 302 0
"GET /login/ HTTP/1.1" 200 2877
"GET /sign-up HTTP/1.1" 200 3939
"POST /sign-up HTTP/1.1" 302 0
"GET /home HTTP/1.1" 200 2032
"GET /summit/ HTTP/1.1" 302 0
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/ HTTP/1.1" 404 179
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /admin/
"GET /admin/ HTTP/1.1" 400 143
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 152, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
"GET /favicon.ico HTTP/1.1" 400 143
"GET /upload HTTP/1.1" 200 2819
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 2370
"GET /static/admin/css/login.css HTTP/1.1" 304 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 2370
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
"GET /static/admin/css/base.css HTTP/1.1" 200 20344
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2619
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 796
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18854
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3763
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/fonts.css HTTP/1.1" 200 423
"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 4736
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
"GET /admin/auth/user/ HTTP/1.1" 200 9715
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6395
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/core.js HTTP/1.1" 200 5698
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8985
"GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 200 89501
"GET /static/admin/js/actions.js HTTP/1.1" 200 7872
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 200 125266
"GET /static/admin/js/filters.js HTTP/1.1" 200 966
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /admin/auth/user/3/change/ HTTP/1.1" 200 17398
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /static/admin/css/forms.css HTTP/1.1" 200 8944
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19379
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4360
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 11317
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11297
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"POST /admin/auth/user/3/change/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 9908
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Not Found: /accounts/login/
"GET /accounts/login/?next=/summit/ HTTP/1.1" 404 179
"GET /home HTTP/1.1" 200 2218
"GET /summit/list/ HTTP/1.1" 200 2467
"GET / HTTP/1.1" 200 2218
"GET /summit/list/ HTTP/1.1" 200 3030
Not Found: /entry
"GET /entry HTTP/1.1" 404 179
Internal Server Error: /summit/entry
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view summit.views.entry didn't return an HttpResponse object. It returned None instead.
"GET /summit/entry HTTP/1.1" 500 145
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /summit/entry HTTP/1.1" 302 0
"GET /summit/list/ HTTP/1.1" 200 3030
Watching for file changes with StatReloader
"GET /summit/entry HTTP/1.1" 302 0
"GET /summit/list/ HTTP/1.1" 200 3030
/home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /summit/list/ HTTP/1.1" 200 3030
"GET /summit/list/ HTTP/1.1" 200 3030
/home/ubuntu/OneForAll/website/summit/summittest.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
Watching for file changes with StatReloader
/home/ubuntu/OneForAll/website/website/settings.py changed, reloading.
Watching for file changes with StatReloader
Scheduler started
Scheduler stopped
"GET /upload HTTP/1.1" 200 3005
"POST /upload HTTP/1.1" 200 26203
"GET /home HTTP/1.1" 200 2218
"GET / HTTP/1.0" 302 0
"GET /summit/list/ HTTP/1.1" 200 2467
"GET / HTTP/1.0" 302 0
"GET / HTTP/1.1" 302 0
"GET /login?next=/ HTTP/1.1" 301 0
"GET /login/?next=/ HTTP/1.1" 200 2877
"GET /upload HTTP/1.1" 200 3005
"GET /summit/list/ HTTP/1.1" 200 2467
"GET /summit/ HTTP/1.1" 200 3573
Forbidden (Permission denied): /create-post
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    if test_func(request.user):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 78, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
"GET /create-post HTTP/1.1" 403 135
"GET /home HTTP/1.1" 200 2218
"GET /upload HTTP/1.1" 200 3005
"GET /summit/list/ HTTP/1.1" 200 2467
"GET /summit/ HTTP/1.1" 200 3573
/home/ubuntu/OneForAll/website/website/settings.py changed, reloading.
2023-02-23 07:35:35 INFO     Watching for file changes with StatReloader
2023-02-23 07:35:37 INFO     Scheduler started
2023-02-23 07:35:37 INFO     Scheduler stopped
2023-02-23 07:35:39 INFO     "GET /upload HTTP/1.1" 200 3005
2023-02-23 07:38:39 INFO     code 400, message Bad request syntax ('MGLNDD_54.250.195.214_8000')
2023-02-23 07:38:39 WARNING  "MGLNDD_54.250.195.214_8000" 400 -
2023-02-23 08:09:39 INFO     /home/ubuntu/OneForAll/website/summit/summittest.py changed, reloading.
2023-02-23 08:09:40 INFO     Watching for file changes with StatReloader
2023-02-23 08:09:42 INFO     Scheduler started
2023-02-23 08:09:42 INFO     Scheduler stopped
2023-02-23 08:10:07 INFO     /home/ubuntu/OneForAll/website/summit/summittest.py changed, reloading.
2023-02-23 08:10:08 INFO     Watching for file changes with StatReloader
2023-02-23 08:10:09 INFO     Scheduler started
2023-02-23 08:10:09 INFO     Scheduler stopped
2023-02-23 08:10:42 INFO     /home/ubuntu/OneForAll/website/summit/scheduler.py changed, reloading.
2023-02-23 08:10:43 INFO     Watching for file changes with StatReloader
2023-02-23 08:10:45 INFO     Scheduler started
2023-02-23 08:10:45 INFO     Scheduler stopped
2023-02-23 08:12:14 INFO     /home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
2023-02-23 08:12:15 INFO     Watching for file changes with StatReloader
2023-02-23 08:12:16 INFO     Scheduler started
2023-02-23 08:12:16 INFO     Scheduler stopped
2023-02-23 08:14:57 INFO     "GET / HTTP/1.1" 302 0
2023-02-23 08:14:58 INFO     "GET /login?next=/ HTTP/1.1" 301 0
2023-02-23 08:14:58 INFO     "GET /login/?next=/ HTTP/1.1" 200 2877
2023-02-23 08:15:02 INFO     "GET /admin/ HTTP/1.1" 302 0
2023-02-23 08:15:03 INFO     "GET / HTTP/1.1" 302 0
2023-02-23 08:15:03 INFO     "GET /login?next=/ HTTP/1.1" 301 0
2023-02-23 08:15:04 INFO     "GET /login/?next=/ HTTP/1.1" 200 2877
2023-02-23 08:15:15 INFO     /home/ubuntu/OneForAll/website/summit/summittest.py changed, reloading.
2023-02-23 08:15:17 INFO     Watching for file changes with StatReloader
2023-02-23 08:15:18 INFO     Scheduler started
2023-02-23 08:15:18 INFO     Scheduler stopped
2023-02-23 08:36:22 INFO     Watching for file changes with StatReloader
2023-02-23 08:45:15 INFO     Watching for file changes with StatReloader
2023-02-23 08:45:37 INFO     /home/ubuntu/OneForAll/website/summit/urls.py changed, reloading.
2023-02-23 08:45:37 INFO     Watching for file changes with StatReloader
2023-02-23 08:49:07 INFO     /home/ubuntu/OneForAll/website/summit/updater.py changed, reloading.
2023-02-23 08:49:08 INFO     Watching for file changes with StatReloader
2023-02-23 08:49:34 INFO     /home/ubuntu/OneForAll/website/summit/views.py changed, reloading.
2023-02-23 08:49:36 INFO     Watching for file changes with StatReloader
